package com.doctorcar.mobile.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.doctorcar.mobile.database.Articles;
import com.doctorcar.mobile.database.User;

import com.doctorcar.mobile.database.dao.ArticlesDao;
import com.doctorcar.mobile.database.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articlesDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ArticlesDao articlesDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articlesDaoConfig = daoConfigMap.get(ArticlesDao.class).clone();
        articlesDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        articlesDao = new ArticlesDao(articlesDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Articles.class, articlesDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        articlesDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ArticlesDao getArticlesDao() {
        return articlesDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
